services:
  mongo1:
    image: mongo:6
    hostname: mongo1
    container_name: mongo1
    ports:
      - 27017:27017
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo1"]

  mongosetup:
    image: mongo:6
    depends_on:
      - mongo1
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: [ "bash", "./scripts/mongo_setup.sh"]
  
  redis:
    image: redis:latest
    ports: 
     - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10

  product-history:
    build:
      context: ./product-history-service
      dockerfile: ./Dockerfile
    restart: always
    env_file: ./product-history-service/.env
    ports:
      - 8080:80
    depends_on:
        redis: 
          condition: service_healthy
        mongo1:
          condition: service_started
        mongosetup:
          condition: service_started

  price-stats:
    build:
      context: ./price-stats-service
      dockerfile: ./Dockerfile
    restart: always
    env_file: ./price-stats-service/.env
    ports:
      - 8081:80
    depends_on:
      redis: 
        condition: service_healthy
      mongo1:
        condition: service_started
      mongosetup:
        condition: service_started

  

